### ISSUE TITLE
Bug: rating curve equation incorrect for added controls

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#66] opened 2024-05-16 14:55 UTC
When several controls are active in a segment, the rating curve equation has only one control... 

e.g. for Meyras, we have:
C1
C2
C3

instead of
C1
C2
C2+C3

To be corrected.

**Comment by IvanHeriver** [comment] 2024-05-16 15:00
Duplicate of issue #67

**Closed by IvanHeriver** 2024-05-16 15:00 UTC
